config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :attached_files
  resources :image_files
  resources :text_contents
  resources :videos
  get 'pages/home'
  resources :tags
  resources :categories
  resources :posts do
    collection do
      match 'search' => 'posts#search', via: %i[get post], as: :search
    end
  end

  # wp-connector endpoints
  match 'wp-post-webhook/:model', to: 'wpconnector#model_create', via: %i[head post]
  match 'wp-put-webhook/:model', to: 'wpconnector#model_update', via: [:put]

  root to: 'pages#home'

  get 'portal', to: 'pages#portal'
  get 'pve', to: 'pages#pve'
  get 'gestores', to: 'pages#gestores'
  get 'mobilizadores', to: 'pages#mobilizadores'
  get 'familias', to: 'pages#familias'
  get 'professores', to: 'pages#professores'
  get 'news', to: 'pages#news'
  
  get '/termos-e-condicoes-de-uso', as: :terms, to: 'pages#terms'
  get '/politica-de-privacidade-e-protecao-de-dados-do-pve', as: :privacy, to: 'pages#privacy'
  
  get '2020/*dt', to: "wpconnector#redirect_wppost"
  get '2019/*dt', to: "wpconnector#redirect_wppost"
  get '2018/*dt', to: "wpconnector#redirect_wppost"
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  belongs_to :parent, class_name: 'Tag', optional: true
  has_many :post_tags
  has_many :posts, through: :post_tags, dependent: :destroy

  def self.create_from_hook(params, post)
    post.tags.destroy_all

    params&.each do |param|
      existing_tag = Tag.where(name: param[1].dig('name'))

      if existing_tag.empty?
        @tag = Tag.new

        @tag.term_wp_id = param[1].dig('term_id')
        @tag.name = param[1].dig('name')
        @tag.slug = param[1].dig('slug')
        @tag.term_group = param[1].dig('term_group')
        @tag.term_taxonomy_id = param[1].dig('term_taxonomy_id')
        @tag.description = param[1].dig('description')
        @tag.parent_wp_id = param[1].dig('parent')
        @tag.count = param[1].dig('count')
        @tag.filter = param[1].dig('filter')
        @tag.taxonomy = param[1].dig('taxonomy')

        if @tag.save
          post.tags << @tag
          @tag
        else
          raise ActiveRecord::RecordNotSaved, 'STOP Wordpress tag creation' \
                                              'Wordpress tag can not be saved'
        end
      else
        puts 'Updating...'
        update_from_hook(param, existing_tag.first, post)
      end
    end
  end

  def self.update_from_hook(param, existing_tag, post)
    existing_tag.description = param[1].dig('description')
    existing_tag.count = param[1].dig('count')

    if existing_tag.save
      post.tags << existing_tag
      existing_tag
    else
      raise ActiveRecord::RecordNotSaved, 'STOP Wordpress tag update' \
                                          'Wordpress tag can not be updated'
    end
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show; end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:term_wp_id, :name, :slug, :term_group, :term_taxonomy_id, :taxonomy, :description, :parent_wp_id, :count, :filter, :parent_id)
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :term_wp_id %>
    <%= form.number_field :term_wp_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :term_group %>
    <%= form.number_field :term_group %>
  </div>

  <div class="field">
    <%= form.label :term_taxonomy_id %>
    <%= form.number_field :term_taxonomy_id %>
  </div>

  <div class="field">
    <%= form.label :taxonomy %>
    <%= form.text_field :taxonomy %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :parent_wp_id %>
    <%= form.number_field :parent_wp_id %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :filter %>
    <%= form.text_field :filter %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.text_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Term wp</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Term group</th>
      <th>Term taxonomy</th>
      <th>Taxonomy</th>
      <th>Description</th>
      <th>Parent wp</th>
      <th>Count</th>
      <th>Filter</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.term_wp_id %></td>
        <td><%= tag.name %></td>
        <td><%= tag.slug %></td>
        <td><%= tag.term_group %></td>
        <td><%= tag.term_taxonomy_id %></td>
        <td><%= tag.taxonomy %></td>
        <td><%= tag.description %></td>
        <td><%= tag.parent_wp_id %></td>
        <td><%= tag.count %></td>
        <td><%= tag.filter %></td>
        <td><%= tag.parent_id %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term wp:</strong>
  <%= @tag.term_wp_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tag.slug %>
</p>

<p>
  <strong>Term group:</strong>
  <%= @tag.term_group %>
</p>

<p>
  <strong>Term taxonomy:</strong>
  <%= @tag.term_taxonomy_id %>
</p>

<p>
  <strong>Taxonomy:</strong>
  <%= @tag.taxonomy %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<p>
  <strong>Parent wp:</strong>
  <%= @tag.parent_wp_id %>
</p>

<p>
  <strong>Count:</strong>
  <%= @tag.count %>
</p>

<p>
  <strong>Filter:</strong>
  <%= @tag.filter %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @tag.parent_id %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>